index.js
Now the production will use hammer.min.js in production, otherwise use hammer.js. For some reason the sourcemap for the minified version was not working with Chrome to trace into hammerjs from an ember app using ember-gestures.
=> chore(build): only use minified hammerjs in production to make debugging easier

addon/services/-gestures.js
Before this fix, it was possible to enter an infinite recursion whereby a recognizer is created over and over ad infinitum because it's not put into the cache immediately upon creation. This was because the recognizer could be created again when creating the included or excluded recognizers. This is avoided by putting the recognizer into the cache immediately, and thus the cached version is retrieved if one of the included or excluded ones depends on the one being created.
=> fix(service): avoid infinite recursion by registering recognizer before includes/excludes.

tests/dummy/app/components/recognizes-single-and-double-tap.js, tests/dummy/app/ember-gestures/recognizers/double-tap.js, tests/dummy/app/ember-gestures/recognizers/single-tap.js, tests/dummy/app/router.js, tests/dummy/app/routes/taps.js, tests/dummy/app/styles/app.css, tests/dummy/app/templates/application.hbs, tests/dummy/app/templates/components/recognizes-single-and-double-tap.hbs, tests/dummy/app/templates/index.hbs, tests/dummy/app/templates/taps.hbs
Single demo for the case when a component wants to recognize a `single-tap` and a `double-tap` in a mutually exclusive way. This works with the `STATE_LIMBO` hack to `hammer.js`, but if there's a way to get it to work with only changes to `ember-gestures` that may be preferable.
=> test(recognizers): demo for a component with both single-tap and double-tap

addon/event_dispatcher.js, addon/services/-gestures.js, app/instance-initializers/ember-gestures.js, bower.json
Running on 2.3 throws a bunch of deprecation warnings.
Unsure what happened to the changes in https://github.com/runspired/ember-gestures/commit/cb4570eb67f0291b4bc5c22850cef4dcdf4551d2 where the polyfill addon was added and some of the lookup calls were changed?
=> fix(deprecations) Use getOwner polyfill for lookup*s

addon/recognizers/swipe.js
It makes swipe recognizer horizontal only. It fixed this issue for me: https://github.com/runspired/ember-gestures/issues/32#issuecomment-173981062. But I'm not sure if it's a correct way to do it :/
=> make swipe recognizer horizontal only

addon/services/-gestures.js
When the gestures service is not able to find a recognizer, it returns a rejected promise with a string literal as the error value. As Ember.js (tested with 2.3.0) is expecting a real Error object and is trying to dump `error.stack` to the console (see https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/ext/rsvp.js#L72), you just get an `undefined` on the console without any message or clue where the error comes from.
This PR fixes it by creating an Error object, giving you the message and the stack trace on the console.
=> Upon failing to find a recognizer reject the promise with a real Error object

blueprints/ember-gestures/index.js, package.json
This is a working fix for #39. Installation of this addon is still not smooth, even after #44 is merged. There is some confusion over what belongs as
* a npm dependency
* a npm devDependency
* a consuming app npm dependency
* a consuming app npm devDependency
I'll reach out to other members of the ember-cli team to see if we can organize some better documentation around this.
=> Add ember-getowner-polyfill as consuming app dep for Ember >= 2.3

blueprints/ember-gestures/index.js
This works around https://github.com/ember-cli/ember-cli/issues/5765
The issue is there are concurrent bower installs and the second starts before the first one settles (writes the update to bower.json).  So when the second install happens it uses the previous read bower.json to append to, writing over the initial entry since it wasn't there when it read `bower.json` into memory.
https://github.com/bower/bower/blob/343e6ac8bcb3ad69a90b2e8c37bf71796417f7b8/lib/core/Project.js#L44 `analyse` here reads bower.json and sets `that._json`
https://github.com/bower/bower/blob/343e6ac8bcb3ad69a90b2e8c37bf71796417f7b8/lib/core/Project.js#L111 writes `that._json` which doesn't contain the content of the first bower install
```
* read
* read (stale)
* write
* write
```
Where it should:
```
* read
* …
```
=> Work around race condition with concurrent bower installs

package.json
Unable to run `ember install ember-cli-version-checker` without this change
It gives me the following error:
``` bash
Installed packages for tooling via npm.
Cannot find module 'ember-cli-version-checker'
Error: Cannot find module 'ember-cli-version-checker'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
```
=> chore(deps) move ember-cli-version-checker to dependencies

app/event_dispatcher.js, app/services/-gestures.js, tests/helpers/start-app.js
Ensures Ember.assign is used where available so no deprecations appear in ember > 2.5
=> Clean nasty Ember.merge deprecations

addon/mixins/recognizers.js, addon/recognizers/pan.js, addon/recognizers/swipe.js, addon/recognizers/vertical-pan.js, addon/recognizers/vertical-swipe.js, addon/services/-gestures.js
Adding Fastboot compatibility.
=> Fastboot compatibility

blueprints/ember-gestures/index.js
ember-getOwner-polyfill should be added to packages if ember version is less than 2.3 and not satisfied
=> ember-getOwner-polyfill fix

addon/event_dispatcher.js
This line causes the following error:
```TypeError: requirejs.entries.hasOwnProperty is not a function```
due to this commit to loader.js: https://github.com/ember-cli/loader.js/commit/8a342966e37844040b6d87a1e72d04d477c1eef5
Using the prototype's hasOwnProperty avoids any surprises.
=> Use Object.prototype.hasOwnProperty for checking if module exists

addon/event_dispatcher.js, addon/mixins/recognizers.js, addon/services/-gestures.js, app/instance-initializers/ember-gestures.js, package.json
`ember-getowner-polyfill` is now a true polyfill and raises deprecations if is used with import
=> fix getOwner deprecations

addon/event_dispatcher.js, addon/mixins/recognizers.js, addon/services/-gestures.js, app/instance-initializers/ember-gestures.js, package.json
Fixes the deprecation introduced in Ember 2.12 `Using "_lookupFactory" is deprecated. Please use container.factoryFor instead.`. Contains the PR #82, so merge this first.
Also moved `ember-getowner-polyfill` from `devDependencies` to `dependencies`.
=> Fix _lookupFactory deprecation

blueprints/ember-gestures/index.js, bower.json, index.js, package.json
Bower is now optional in ember, so it makes sense to pull in the deps using npm
=> Remove dependency on bower

README.md, package.json
Since html-next seems to be the new home for ember-gestures the links should also be pointing to this repository.
=> docs(general) changed links pointing to runspired to html-next

addon/styles/app.css
The styles are compatible with IE9+ and removes the following linting error: `Gradient has outdated direction syntax. New syntax is like 'to left' instead of 'right'`
=> Update styles to match modern browser standards

addon/components/gesture-element.js, addon/event_dispatcher.js, addon/services/-gestures.js, addon/utils/string/cap-first-letter.js, addon/utils/string/capitalize-word.js, addon/utils/string/capitalize-words.js, addon/utils/string/dasherized-to-camel.js, addon/utils/string/dasherized-to-words.js, addon/utils/string/strip-whitespace.js, addon/utils/string/uncapitalize-word.js, package.json, tests/unit/utils/string-test.js, yarn.lock
Removes ember-allpurpose dependency.  The dependency is only used in 3(ish) places, and contributes about 9k worth of utilities.   Found this out when reviewing an app with broccoli-concat-analyzer: 
Pulled the exact functions used within ember-allpurpose.  We lose the ability for these to be updated, but they seem stable enough to pull in this way and will save 9k compressed payload to anyone using this lib.
:beers:
=> Remove ember-allpurpose

addon/event_dispatcher.js
Remove depreciated canDispatchToEventManager
Depreciated Message:
```
DEPRECATION: `canDispatchToEventManager` has been deprecated in (EventDispatcher). [deprecation id: ember-views.event-dispatcher.canDispatchToEventManager]
at logDeprecationStackTrace (http://school1.bloowatch.com/assets/vendor.js:29457:21)
at HANDLERS.(anonymous function) (http://school1.bloowatch.com/assets/vendor.js:29669:9)
at raiseOnDeprecation (http://school1.bloowatch.com/assets/vendor.js:29487:14)
at HANDLERS.(anonymous function) (http://school1.bloowatch.com/assets/vendor.js:29669:9)
at invoke (http://school1.bloowatch.com/assets/vendor.js:29681:9)
at deprecate (http://school1.bloowatch.com/assets/vendor.js:29541:24)
at Class.init (http://school1.bloowatch.com/assets/vendor.js:62815:87)
at Class.superWrapper …
```
=> Remove depreciated canDispatchToEventManager

addon/event_dispatcher.js
The wrong resolution of ```rootElement``` causes  the cleanup of eventHandlers to fail and thus leads to a memory leak.
=> bugfix(rootElementResolution): fixes #118 wrong resolution of rootElement 

.travis.yml, config/ember-try.js, package.json, yarn.lock
This will require a major version bump as we will no longer be supporting Node 4 or Node 6.
=> Bump the minimum node version to 8, ember-cli-babel and ember-qunit versions

CHANGELOG.md, README.md, addon/modifiers/recognize-gesture.js, app/ember-gestures/modifiers/recognize-gestures.js, app/modifiers/recognize-gesture.js, config/dependency-lint.js, package.json, tests/dummy/app/components/single-and-double-tap-modifier.js, tests/dummy/app/router.js, tests/dummy/app/routes/modtaps.js, tests/dummy/app/templates/components/single-and-double-tap-modifier.hbs, tests/dummy/app/templates/index.hbs, tests/dummy/app/templates/modtaps.hbs, yarn.lock
I created a modifier to do what the recognizer mixin does, so I can use tagName="" and apply it to an element in the template.  The modifier can only be used in Ember 2.18 or later, but its presence doesn't seem to affect building or testing code in lower versions, as long as that code doesn't try to use it. 
I added a paragraph to the README but I'm not sure what I should add for test automation. There should be something, at least in the dummy app. On the other hand, there don't seem to be a lot of other tests in the suite that I could use for inspiration.
=> feature(modifier): Add recognize-gesture modifier

README.md
To me it wasn't obvious that these two recognizers were not in fact packaged with the addon because they are in the recognizer folder
=> Added more clarity about double-tap/single-tap

package.json, yarn.lock
This indirectly upgrades ember-cli-babel, as ember-copy 1.0 depends on ember-cli-babel v6, while ember-copy 2.0 depends on ember-cli-babel v7.
=> Upgrade ember-copy to v2
